name: pemobile2_d4rpl3a_praktikum4
description: "Project Slicing UI dari Desain Figma yang telah disediakan"
publish_to: 'none'

version: 1.0.3

environment:
  sdk: '>=2.19.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/bd_flag.png  
